add Terraform Test to module
aws-ia/terraform-aws-label pull request #4
Opened 2021-11-30 20:17 UTC by drewmullen

provide acceptance tests using `terraform test`

2021-12-01 01:36 UTC, drewmullen commented on tests/examples_formatted_tags/test.tf
> +    condition   = length(setsubtract(local.awscc_tags_formatted["test_aws_to_awscc"], local.awscc_tags_formatted["test_awscc_to_awscc"])) == 0
yes this is a good point. was only checking 1 direction 😬

2021-12-02 21:17 UTC, andrew-glenn commented
Note: https://github.com/hashicorp/terraform/issues/30071 is relevant.

2021-12-02 21:18 UTC, andrew-glenn requested changes
Preventing merge for now, due to underlying issue discovered regarding `terraform test` and implicit dependencies.

2022-02-03 15:09 UTC, drewmullen commented
Closing - pending future releases of `terraform test` we can re-evaluate

2022-02-03 15:09 UTC, closed without merging